import { ApiKeyRecord, DashboardStats, Lead, SearchHistoryItem } from '../types';

export const INITIAL_MOCK_LEADS: Lead[] = [
  {
    id: 'lead-001',
    businessName: 'Apex Peak Digital Media',
    niche: 'Digital Marketing',
    industry: 'Marketing & Advertising',
    category: 'Digital Agency',
    subcategory: 'Performance Marketing',
    businessType: 'Agency',
    serviceType: 'Omnichannel Paid Search & PPC',
    productType: 'B2B Lead Generation Retainers',
    companySize: '11-50',
    businessModel: 'B2B',
    businessStage: 'Established',
    locationType: 'Local',
    country: 'USA',
    state: 'New York',
    city: 'New York City',
    district: 'Manhattan',
    area: 'SoHo',
    zipCode: '10012',
    address: '452 Broadway, Floor 4, New York, NY 10012',
    serviceArea: 'Greater New York Metro',
    website: 'https://apexpeakmedia.com',
    hasWebsite: true,
    httpsAvailable: true,
    customDomain: true,
    websitePlatform: 'WordPress',
    websiteStatus: 'Active',
    websiteLanguage: 'English',
    publicEmail: 'contact@apexpeakmedia.com',
    hasEmail: true,
    emailType: 'Business Domain',
    emailDepartment: 'Contact',
    emailStatus: 'Valid',
    isDisposableEmail: false,
    isRoleBasedEmail: true,
    domainValid: true,
    mxAvailable: true,
    phone: '+1 (212) 555-0192',
    hasPhone: true,
    hasContactForm: true,
    businessStatus: 'Active',
    socialProfiles: {
      linkedin: 'https://linkedin.com/company/apex-peak-media',
      twitter: 'https://x.com/apexpeakdigital',
      facebook: 'https://facebook.com/apexpeakmedia',
    },
    hasSocialProfile: true,
    leadScore: 94,
    scoreTier: 'High Quality',
    scoreBreakdown: {
      totalScore: 94,
      maxScore: 100,
      tier: 'High Quality',
      summary: 'Exceptional public business presence with corporate domain and verified security.',
      factors: [
        { name: 'Custom Domain Website with SSL', points: 25, maxPoints: 25, passed: true, explanation: 'Verified secure custom domain.' },
        { name: 'Validated Corporate Email', points: 30, maxPoints: 30, passed: true, explanation: 'Corporate domain email with valid MX records.' },
        { name: 'Full Contact Channels', points: 15, maxPoints: 15, passed: true, explanation: 'Public telephone and address present.' },
        { name: 'Social Authority Presence', points: 14, maxPoints: 15, passed: true, explanation: 'Verified LinkedIn and Twitter profiles.' },
        { name: 'Established Enterprise Stage', points: 10, maxPoints: 15, passed: true, explanation: 'Established 11-50 team.' },
      ],
    },
    sourceUrl: 'https://www.publicbusinessregistry.ny.gov/entity/apexpeakmedia',
    sourceType: 'Public Business Directory',
    firstDiscovered: '2026-02-14T08:30:00Z',
    lastChecked: '2026-03-12T14:15:00Z',
    isDuplicate: false,
    dataCompleteness: 'Complete Lead',
    tags: ['High Value', 'PPC Partner'],
    notes: 'Top performing agency in Manhattan with high marketing budget.',
    isSaved: true,
    createdAt: '2026-02-14T08:30:00Z',
    updatedAt: '2026-03-12T14:15:00Z',
  },
  {
    id: 'lead-002',
    businessName: 'Vanguard Cloud Architecture',
    niche: 'Software & SaaS',
    industry: 'Technology',
    category: 'Enterprise Software',
    subcategory: 'Cloud Engineering',
    businessType: 'Company',
    serviceType: 'Multi-Cloud Migration & Kubernetes',
    productType: 'DevOps & Cloud Orchestration',
    companySize: '51-200',
    businessModel: 'B2B',
    businessStage: 'Established',
    locationType: 'Hybrid',
    country: 'UK',
    state: 'Greater London',
    city: 'London',
    district: 'City of London',
    area: 'Shoreditch',
    zipCode: 'EC2A 4NE',
    address: '14 Tech Square, London EC2A 4NE, UK',
    serviceArea: 'United Kingdom & Europe',
    website: 'https://vanguardcloud.co.uk',
    hasWebsite: true,
    httpsAvailable: true,
    customDomain: true,
    websitePlatform: 'Custom Website',
    websiteStatus: 'Active',
    websiteLanguage: 'English',
    publicEmail: 'hello@vanguardcloud.co.uk',
    hasEmail: true,
    emailType: 'Business Domain',
    emailDepartment: 'General',
    emailStatus: 'Valid',
    isDisposableEmail: false,
    isRoleBasedEmail: true,
    domainValid: true,
    mxAvailable: true,
    phone: '+44 20 7946 0831',
    hasPhone: true,
    hasContactForm: true,
    businessStatus: 'Active',
    socialProfiles: {
      linkedin: 'https://linkedin.com/company/vanguard-cloud',
      twitter: 'https://x.com/vanguardcloud',
    },
    hasSocialProfile: true,
    leadScore: 92,
    scoreTier: 'High Quality',
    scoreBreakdown: {
      totalScore: 92,
      maxScore: 100,
      tier: 'High Quality',
      summary: 'Robust enterprise tech footprint with comprehensive public channels.',
      factors: [
        { name: 'Custom Domain Website with SSL', points: 25, maxPoints: 25, passed: true, explanation: 'Verified secure custom domain.' },
        { name: 'Validated Corporate Email', points: 30, maxPoints: 30, passed: true, explanation: 'Corporate domain email with valid MX.' },
        { name: 'Full Contact Channels', points: 15, maxPoints: 15, passed: true, explanation: 'Public phone and registered London office.' },
        { name: 'Social Authority Presence', points: 12, maxPoints: 15, passed: true, explanation: 'Verified LinkedIn profile.' },
        { name: 'Established Enterprise Stage', points: 10, maxPoints: 15, passed: true, explanation: '51-200 team members.' },
      ],
    },
    sourceUrl: 'https://find-and-update.company-information.service.gov.uk/company/vanguardcloud',
    sourceType: 'Public Business Directory',
    firstDiscovered: '2026-02-18T11:20:00Z',
    lastChecked: '2026-03-14T09:00:00Z',
    isDuplicate: false,
    dataCompleteness: 'Complete Lead',
    tags: ['Tech Enterprise'],
    notes: '',
    isSaved: false,
    createdAt: '2026-02-18T11:20:00Z',
    updatedAt: '2026-03-14T09:00:00Z',
  },
  {
    id: 'lead-003',
    businessName: 'Lumina Studio Works',
    niche: 'Web Design',
    industry: 'Information Technology',
    category: 'Creative Studio',
    subcategory: 'UI/UX Design',
    businessType: 'Agency',
    serviceType: 'Design Systems & Interactive Prototypes',
    productType: 'Webflow Development & Figma Systems',
    companySize: '1-10',
    businessModel: 'B2B',
    businessStage: 'Startup',
    locationType: 'Online',
    country: 'Canada',
    state: 'Ontario',
    city: 'Toronto',
    district: 'Downtown Core',
    area: 'King West',
    zipCode: 'M5V 2H1',
    address: '88 King St West, Toronto, ON M5V 2H1',
    serviceArea: 'North America',
    website: 'https://luminastudio.design',
    hasWebsite: true,
    httpsAvailable: true,
    customDomain: true,
    websitePlatform: 'Webflow',
    websiteStatus: 'Active',
    websiteLanguage: 'English',
    publicEmail: 'inquiries@luminastudio.design',
    hasEmail: true,
    emailType: 'Business Domain',
    emailDepartment: 'Info',
    emailStatus: 'Valid',
    isDisposableEmail: false,
    isRoleBasedEmail: false,
    domainValid: true,
    mxAvailable: true,
    phone: '+1 (416) 555-0849',
    hasPhone: true,
    hasContactForm: true,
    businessStatus: 'Active',
    socialProfiles: {
      instagram: 'https://instagram.com/luminastudioworks',
      linkedin: 'https://linkedin.com/company/lumina-studio-works',
    },
    hasSocialProfile: true,
    leadScore: 88,
    scoreTier: 'High Quality',
    scoreBreakdown: {
      totalScore: 88,
      maxScore: 100,
      tier: 'High Quality',
      summary: 'High quality creative studio with modern Webflow platform.',
      factors: [
        { name: 'Custom Domain Website with SSL', points: 25, maxPoints: 25, passed: true, explanation: 'Verified secure custom domain.' },
        { name: 'Validated Corporate Email', points: 30, maxPoints: 30, passed: true, explanation: 'Custom domain email with valid MX.' },
        { name: 'Full Contact Channels', points: 15, maxPoints: 15, passed: true, explanation: 'Phone and contact form available.' },
        { name: 'Social Authority Presence', points: 10, maxPoints: 15, passed: true, explanation: 'Instagram & LinkedIn active.' },
        { name: 'Established Enterprise Stage', points: 8, maxPoints: 15, passed: true, explanation: 'Boutique agency.' },
      ],
    },
    sourceUrl: 'https://www.canadacompanyregistry.ca/luminastudio',
    sourceType: 'Public Business Directory',
    firstDiscovered: '2026-03-01T14:40:00Z',
    lastChecked: '2026-03-15T16:20:00Z',
    isDuplicate: false,
    dataCompleteness: 'Complete Lead',
    tags: ['Design Partner'],
    notes: 'Award winning UI designers.',
    isSaved: true,
    createdAt: '2026-03-01T14:40:00Z',
    updatedAt: '2026-03-15T16:20:00Z',
  },
  {
    id: 'lead-004',
    businessName: 'Velocita Logistics & Freight',
    niche: 'E-commerce',
    industry: 'Retail & Commerce',
    category: 'Online Store',
    subcategory: 'Direct-to-Consumer',
    businessType: 'Company',
    serviceType: 'Same-Day Regional Delivery & Fulfillment',
    productType: 'Cross-Border Supply Chain Storage',
    companySize: '201-500',
    businessModel: 'Both',
    businessStage: 'Established',
    locationType: 'Hybrid',
    country: 'Australia',
    state: 'New South Wales',
    city: 'Sydney',
    district: 'CBD',
    area: 'Surry Hills',
    zipCode: '2010',
    address: '320 Elizabeth St, Sydney NSW 2010',
    serviceArea: 'Oceania & APAC',
    website: 'https://velocitalogistics.com.au',
    hasWebsite: true,
    httpsAvailable: true,
    customDomain: true,
    websitePlatform: 'Shopify',
    websiteStatus: 'Active',
    websiteLanguage: 'English',
    publicEmail: 'support@velocitalogistics.com.au',
    hasEmail: true,
    emailType: 'Business Domain',
    emailDepartment: 'Support',
    emailStatus: 'Valid',
    isDisposableEmail: false,
    isRoleBasedEmail: true,
    domainValid: true,
    mxAvailable: true,
    phone: '+61 2 9123 4567',
    hasPhone: true,
    hasContactForm: true,
    businessStatus: 'Active',
    socialProfiles: {
      linkedin: 'https://linkedin.com/company/velocita-logistics',
    },
    hasSocialProfile: true,
    leadScore: 85,
    scoreTier: 'High Quality',
    scoreBreakdown: {
      totalScore: 85,
      maxScore: 100,
      tier: 'High Quality',
      summary: 'Established logistics provider with active multichannel operations.',
      factors: [
        { name: 'Custom Domain Website with SSL', points: 25, maxPoints: 25, passed: true, explanation: 'Verified secure custom domain.' },
        { name: 'Validated Corporate Email', points: 30, maxPoints: 30, passed: true, explanation: 'Corporate domain email.' },
        { name: 'Full Contact Channels', points: 15, maxPoints: 15, passed: true, explanation: 'Phone and contact form available.' },
        { name: 'Social Authority Presence', points: 5, maxPoints: 15, passed: false, explanation: 'Limited social channels.' },
        { name: 'Established Enterprise Stage', points: 10, maxPoints: 15, passed: true, explanation: 'Enterprise scale 201-500.' },
      ],
    },
    sourceUrl: 'https://abr.business.gov.au/ABN/View?id=8923478912',
    sourceType: 'Public Business Directory',
    firstDiscovered: '2026-02-10T12:00:00Z',
    lastChecked: '2026-03-10T11:00:00Z',
    isDuplicate: false,
    dataCompleteness: 'Complete Lead',
    tags: [],
    notes: '',
    isSaved: false,
    createdAt: '2026-02-10T12:00:00Z',
    updatedAt: '2026-03-10T11:00:00Z',
  },
  {
    id: 'lead-005',
    businessName: 'Skyline Media Dhaka',
    niche: 'Digital Marketing',
    industry: 'Marketing & Advertising',
    category: 'Digital Agency',
    subcategory: 'Performance Marketing',
    businessType: 'Agency',
    serviceType: 'Social Media Strategy & Production',
    productType: 'Agency Retainers',
    companySize: '11-50',
    businessModel: 'B2B',
    businessStage: 'Established',
    locationType: 'Local',
    country: 'Bangladesh',
    state: 'Dhaka Division',
    city: 'Dhaka',
    district: 'Gulshan',
    area: 'Banani',
    zipCode: '1213',
    address: 'Road 11, Block D, Banani, Dhaka 1213',
    serviceArea: 'Bangladesh & South Asia',
    website: 'https://skylinemedia.com.bd',
    hasWebsite: true,
    httpsAvailable: true,
    customDomain: true,
    websitePlatform: 'Custom Website',
    websiteStatus: 'Active',
    websiteLanguage: 'Bangla',
    publicEmail: 'info@skylinemedia.com.bd',
    hasEmail: true,
    emailType: 'Business Domain',
    emailDepartment: 'Info',
    emailStatus: 'Valid',
    isDisposableEmail: false,
    isRoleBasedEmail: true,
    domainValid: true,
    mxAvailable: true,
    phone: '+880 1711 000000',
    hasPhone: true,
    hasContactForm: true,
    businessStatus: 'Active',
    socialProfiles: {
      linkedin: 'https://linkedin.com/company/skylinemediabd',
      facebook: 'https://facebook.com/skylinemediabd',
    },
    hasSocialProfile: true,
    leadScore: 90,
    scoreTier: 'High Quality',
    scoreBreakdown: {
      totalScore: 90,
      maxScore: 100,
      tier: 'High Quality',
      summary: 'Verified agency with corporate domain in Banani, Dhaka.',
      factors: [
        { name: 'Custom Domain Website with SSL', points: 25, maxPoints: 25, passed: true, explanation: 'Secure corporate website.' },
        { name: 'Validated Corporate Email', points: 30, maxPoints: 30, passed: true, explanation: 'Corporate email.' },
        { name: 'Full Contact Channels', points: 15, maxPoints: 15, passed: true, explanation: 'Phone and office address.' },
        { name: 'Social Authority Presence', points: 10, maxPoints: 15, passed: true, explanation: 'Facebook & LinkedIn presence.' },
        { name: 'Established Enterprise Stage', points: 10, maxPoints: 15, passed: true, explanation: 'Established 11-50 team.' },
      ],
    },
    sourceUrl: 'https://roc.gov.bd/skylinemedia',
    sourceType: 'Public Business Directory',
    firstDiscovered: '2026-02-15T09:00:00Z',
    lastChecked: '2026-03-15T09:00:00Z',
    isDuplicate: false,
    dataCompleteness: 'Complete Lead',
    tags: ['South Asia', 'Digital Agency'],
    notes: 'Premier Banani agency.',
    isSaved: true,
    createdAt: '2026-02-15T09:00:00Z',
    updatedAt: '2026-03-15T09:00:00Z',
  }
];

export const MOCK_HISTORY: SearchHistoryItem[] = [
  {
    id: 'hist-01',
    querySummary: 'Digital Marketing in USA, UK, Bangladesh',
    filters: {
      countries: ['USA', 'UK', 'Bangladesh'],
      niche: 'Digital Marketing',
    },
    timestamp: '2026-03-16T18:40:00Z',
    resultCount: 284,
    durationMs: 420,
    status: 'Completed',
  },
];

export const MOCK_API_KEYS: ApiKeyRecord[] = [
  {
    id: 'key-01',
    name: 'Production Scraper Bot',
    keyPrefix: 'alc_live_••••39a1',
    keyHash: 'hash_99a7b483',
    createdAt: '2026-03-01T10:00:00Z',
    lastUsedAt: '2026-03-16T12:00:00Z',
    requestsCount: 14820,
    isActive: true,
  },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalLeads: 420,
  validEmails: 378,
  websitesFound: 395,
  highQualityLeads: 294,
  searchesToday: 48,
  apiUsageToday: 1250,
  recentSearches: MOCK_HISTORY,
  recentLeads: INITIAL_MOCK_LEADS,
  charts: {
    leadsOverTime: [
      { date: 'Mar 10', count: 45 },
      { date: 'Mar 11', count: 62 },
      { date: 'Mar 12', count: 85 },
      { date: 'Mar 13', count: 110 },
      { date: 'Mar 14', count: 142 },
      { date: 'Mar 15', count: 198 },
      { date: 'Mar 16', count: 420 },
    ],
    leadsByCountry: [
      { country: 'USA', count: 145 },
      { country: 'UK', count: 82 },
      { country: 'Canada', count: 48 },
      { country: 'Australia', count: 39 },
      { country: 'Germany', count: 35 },
      { country: 'Bangladesh', count: 30 },
      { country: 'Other', count: 41 },
    ],
    leadsByNiche: [
      { niche: 'Digital Marketing', count: 76 },
      { niche: 'Software & SaaS', count: 68 },
      { niche: 'Web Design', count: 54 },
      { niche: 'Real Estate', count: 48 },
      { niche: 'Healthcare', count: 42 },
      { niche: 'E-commerce', count: 34 },
      { niche: 'Other', count: 98 },
    ],
    emailStatusDistribution: [
      { status: 'Valid', count: 378, percentage: 90 },
      { status: 'Risky', count: 24, percentage: 6 },
      { status: 'Invalid', count: 10, percentage: 2 },
      { status: 'Unknown', count: 8, percentage: 2 },
    ],
    qualityDistribution: [
      { tier: 'High Quality', count: 294, percentage: 70 },
      { tier: 'Medium Quality', count: 102, percentage: 24 },
      { tier: 'Low Quality', count: 24, percentage: 6 },
    ],
  },
};
